syntax = "proto3";

package cart;

// Cart Service definition
service CartService {
  rpc GetCart(GetCartRequest) returns (GetCartResponse);
  rpc ClearCart(ClearCartRequest) returns (ClearCartResponse);
}

// Request to get a cart
message GetCartRequest {
  int32 userId = 1;
}

// A cart item
message CartItem {
  string productId = 1;
  string name = 2;
  double price = 3;
  int32 quantity = 4;
}

// Response for GetCart
message GetCartResponse {
  repeated CartItem items = 1;
  double totalPrice = 2;
  int32 totalQuantity = 3;
}

// Request to clear cart
message ClearCartRequest {
  int32 userId = 1;
}

// Response for ClearCart
message ClearCartResponse {
  string message = 1;
}
