apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
  namespace: e-commerce
data:
  DEBUG: "False"
  SECRET_KEY: "django-insecure-prod-key"
  ALLOWED_HOSTS: "user-service,localhost"
  GRPC_PORT: "9003"
  DSN_PRODUCT: "host=postgres port=5432 user=postgres password=password dbname=product_service sslmode=disable timezone=UTC connect_timeout=5"
  DSN_PAYMENT: "host=postgres port=5432 user=postgres password=password dbname=payment_service sslmode=disable timezone=UTC connect_timeout=5"
  DATABASE_URL_USER: "postgres://postgres:password@postgres:5432/user_service_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
  MONGODB_URI: "mongodb://mongo:27017/order_service"
